# Generated by Django 4.2.3 on 2023-07-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_address_profile_city_profile_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobile_number',
            new_name='phone_number',
        ),
    ]
