# Generated by Django 4.2.3 on 2023-08-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_mobile_number_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
